server {
    listen 80;
    listen [::]:80;
    server_name осознанныйвыбор.рф www.осознанныйвыбор.рф;
    
    root /var/www/осознанныйвыбор.рф;
    index index.html;
    
    # Favicon без ошибки 404
    location = /favicon.ico {
        log_not_found off;
        access_log off;
        return 204;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}

